name: CI/CD Pipeline - Portal Orc Front-End

on:
  push:
    branches: [ "main", "master", "developer" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Testar Build do Container Docker
      run: docker build -t portal-orc-test ./frontend
    
    - name: Testar Build do Container Docker
      run: docker build -t portal-orc-test ./backend
